# Generated by Django 6.0.5 on 2026-05-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_subscription_monthly_cost_plan_monthly_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='next_payment_date',
            new_name='end_date',
        ),
    ]
