# Generated by Django 6.0.5 on 2026-05-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_next_payment_date_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='monthly_cost',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
