# Generated by Django 6.0.5 on 2026-05-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_plan_monthly_cost_subscription_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
