# Generated by Django 6.0.5 on 2026-05-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.platform'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
