# Generated by Django 6.0.5 on 2026-06-04 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_platform_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expensereport',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='report_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='subscription_end_after_start'),
        ),
    ]
