# Generated by Django 6.0.5 on 2026-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_expensereport_report_end_after_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_date',
            field=models.DateField(default="2026-12-30"),
            preserve_default=False,
        ),
    ]
